//This file was generated by the Gradle 'init' task.
 
plugins {
    application
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.3")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.9.3")
    implementation("com.google.guava:guava:31.1-jre")
    implementation("mysql:mysql-connector-java:8.0.33")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

application {
    mainClass.set("org.example.virusescapegame")
}
tasks.named<Test>("test") {
    useJUnitPlatform()
}
